// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace Openbanking_Investec_DashboardML.Model
{
    public class ModelInput
    {
        [ColumnName("col0"), LoadColumn(0)]
        public float Col0 { get; set; }


        [ColumnName("col1"), LoadColumn(1)]
        public float Col1 { get; set; }


        [ColumnName("col2"), LoadColumn(2)]
        public string Col2 { get; set; }


        [ColumnName("col3"), LoadColumn(3)]
        public string Col3 { get; set; }


        [ColumnName("col4"), LoadColumn(4)]
        public string Col4 { get; set; }


        [ColumnName("col5"), LoadColumn(5)]
        public string Col5 { get; set; }


        [ColumnName("col6"), LoadColumn(6)]
        public string Col6 { get; set; }


        [ColumnName("col7"), LoadColumn(7)]
        public string Col7 { get; set; }


        [ColumnName("col8"), LoadColumn(8)]
        public string Col8 { get; set; }


        [ColumnName("col9"), LoadColumn(9)]
        public float Col9 { get; set; }


        [ColumnName("col10"), LoadColumn(10)]
        public string Col10 { get; set; }


        [ColumnName("col11"), LoadColumn(11)]
        public float Col11 { get; set; }


    }
}
